# This file is part of unit-utilization.
# https://github.com/garnertb/unit-utilization

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2017, Tyler Garner <garnertb@prominentedge.com>

language: python

python:
    - "2.7"
    - "3.4"
    - "pypy"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
